#!/bin/bash

export CC=i686-qtum-gcc
export LD=i686-qtum-ld
export CXX=i686-qtum-g++
export CPP=i686-qtum-cpp
export AR=i686-qtum-ar
export STRIP=i686-qtum-strip
export OBJCOPY=i686-qtum-objcopy

cd ${HOME}/bind

make "$@"