FROM alpine:3.9.4
LABEL maintainers "earlz, VoR0220"

RUN apk update && apk add git \ 
                          make \
                          cmake \
                          file \
                          autoconf \
                          automake \ 
                          build-base \
                          libtool \
                          db-c++ \
                          db-dev \
                          boost-system \
                          boost-program_options \
                          boost-filesystem \ 
                          boost-dev \ 
                          libressl-dev \ 
                          libevent-dev 