#!/bin/sh

set -e

case $QTUM_NETWORK in
  regtest)
    SELECT_NETWORK=-regtest
    ;;
  testnet)
    SELECT_NETWORK=-testnet
    ;;
  mainnet)
    SELECT_NETWORK=-testnet
    ;;
  *)
    echo "Unknown network: $QTUM_NETWORK"
    exit 1
esac

mkdir -p $QTUM_DATADIR

exec qtumd ${SELECT_NETWORK} \
  -rpcbind=0.0.0.0:3889 -rpcallowip=172.17.0.0/16 \
  -datadir=$QTUM_DATADIR \
  -logevents -reindex-chainstate \
  -rpcuser=$QTUM_RPC_USER -rpcpassword=$QTUM_RPC_PASS \
  -printtoconsole
