FROM alpine:3.9.4
LABEL maintainers "earlz, VoR0220"

RUN apk update && apk add git \
							make \
							cmake \
							musl	\
							alpine-sdk \
							texinfo \
							bison \
							flex \
							yasm \
							perl-utils \
							autoconf \
							automake \
							libtool \
							db-dev \
							boost \
							boost-system \
                          	boost-program_options \
                          	boost-filesystem \ 
                          	boost-dev \ 
							openssl-dev \
							libevent-dev